import { Phone } from "./phonesTableSlice";

export function initPhones(): Phone[] {
  return [
    {
      id: "1",
      name: "Apple iPhone 12",
      photo: "/images/phones/iphone_12.png",
      icon: "/images/phones/iphone_12_small.png",
      producer: "Apple",
      releaseYear: 2020,
      diagonal: 6.1,
      countryOfProducer: "Китай",
      storage: 128,
      frequency: 60,
      nfc: false,
      esim: true,
      wirelessCharging: true,
      price: 81990,
    },
    {
      id: "2",
      name: "Xiaomi Mi 11 Lite",
      photo: "/images/phones/xiaomi_mi_11lite.png",
      icon: "/images/phones/xiaomi_mi_11lite_small.png",
      producer: "Xiaomi",
      releaseYear: 2021,
      diagonal: 6.55,
      countryOfProducer: "Китай",
      storage: 128,
      frequency: 90,
      nfc: true,
      esim: true,
      wirelessCharging: false,
      price: 27490,
    },
    {
      id: "3",
      name: "Samsung Galaxy A72",
      photo: "/images/phones/samsung_a72.png",
      icon: "/images/phones/samsung_a72_small.png",
      producer: "Samsung",
      releaseYear: 2021,
      diagonal: 6.7,
      countryOfProducer: "Вьетнам",
      storage: 128,
      frequency: 90,
      nfc: true,
      esim: false,
      wirelessCharging: true,
      price: 32890,
    },
    {
      id: "4",
      name: "Samsung Galaxy S21",
      photo: "/images/phones/samsung_s21.png",
      icon: "/images/phones/samsung_s21_small.png",
      producer: "Samsung",
      releaseYear: 2021,
      diagonal: 6.2,
      countryOfProducer: "Вьетнам",
      storage: 128,
      frequency: 120,
      nfc: true,
      esim: true,
      wirelessCharging: true,
      price: 46395,
    },
    {
      id: "5",
      name: "Apple iPhone Xr",
      photo: "/images/phones/iphone_xr.png",
      icon: "/images/phones/iphone_xr_small.png",
      producer: "Apple",
      releaseYear: 2018,
      diagonal: 6.1,
      countryOfProducer: "Китай",
      storage: 64,
      frequency: 60,
      nfc: true,
      esim: true,
      wirelessCharging: true,
      price: 31195,
    },
    {
      id: "6",
      name: "Realme 8 Pro",
      photo: "/images/phones/realme_8pro.png",
      icon: "/images/phones/realme_8pro_small.png",
      producer: "Realme",
      releaseYear: 2020,
      diagonal: 6.4,
      countryOfProducer: "Китай",
      storage: 128,
      frequency: 120,
      nfc: true,
      esim: false,
      wirelessCharging: false,
      price: 19490,
    },
  ];
}
